name = "rvy/spin"
version = "0.0.4"
authors = ["rvy"]
license = "MIT"
description = "Terminal spinners with dynamic text updates and CI support."
repository = "https://github.com/revvy02/spin"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src/**/*.luau",
  ".luaurc",
]

[engines]
lune = "^0.10.4"
pesde = "^0.7.1"

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
selene = { name = "pesde/selene", version = "^0.29.0+toolchainlib.1", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.3.0", target = "lune" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.55.0", target = "lune" }