name = "rvy/spin"
version = "0.0.1"

[engines]
lune = "^0.10.4"
pesde = "^0.7.1"

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
selene = { name = "pesde/selene", version = "^0.29.0+toolchainlib.1", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.3.0", target = "lune" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.55.0", target = "lune" }